unbind-key C-b
set-option -g prefix C-j
bind-key C-j send-prefix

set -g default-terminal 'screen-256color'
set -g terminal-overrides 'xterm:colors=256'

set-environment -g TZ Asia/Tokyo


set -s escape-time 0
set-option -g mouse on

# message表示時のstatus lineの色。dispaly,confirm-before -p などのコマンド出力の色
#set -g message-style fg=colour68,reverse,bg=brightwhite

set -g pane-border-status bottom
set -g pane-border-format "#{pane_index}:#{pane_current_command}"
set -g status-interval 1
bind-key -T edit-mode-vi WheelUpPane send-keys -X scroll-up
bind-key -T edit-mode-vi WheelDownPane send-keys -X scroll-down
bind S set-window-option synchronize-panes

# アクティブウィンドウの色
setw -g window-status-current-style fg=cyan,bg=default,dim

# アクティブペインの枠線色を藍色に変更
set -g pane-active-border-style "fg=colour39"

# 非アクティブペインの枠線色（必要に応じて設定）
set -g pane-border-style "fg=grey"

# コマンドラインの色
set -g message-style fg=white,bg=black,dim

# ステータスバーの色
set -g status-fg white
set -g status-bg '#444444'


# コピーモードのハイライト
set -g mode-style "fg=default,bg=default,reverse"
# macOS用クリップボード連携
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
