format = """
[░▒▓](#E6D6A8)\
$os\
[](fg:#E6D6A8)\
[ ](fg:#B99A5B)\
$username\
$hostname\
[](fg:#B99A5B)\
[ ](fg:#A08A5A)\
$directory\
[](fg:#A08A5A bg:#33291C)\
$git_branch\
$git_status\
[](fg:#33291C bg:#1F1A13)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#1F1A13 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character
"""

[username]
style_user = "fg:#ffffff bg:#B99A5B"
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = false
style = "fg:#ffffff bg:#B99A5B"
format = "[@$hostname]($style)"

[directory]
style = "fg:#ffffff bg:#A08A5A"
read_only = ''
format = '[ $path ]($style)[$read_only]($style)'
truncation_length = 0
truncate_to_repo = false
use_os_path_sep = true

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#33291C"
format = '[[ $symbol $branch ](fg:#A08A5A bg:#33291C)]($style)'

[git_status]
style = "bg:#33291C"
format = '[[($all_status$ahead_behind )](fg:#A08A5A bg:#33291C)]($style)'

[nodejs]
symbol = ""
style = "bg:#1F1A13"
format = '[[ $symbol ($version) ](fg:#8A7144 bg:#1F1A13)]($style)'

[rust]
symbol = ""
style = "bg:#1F1A13"
format = '[[ $symbol ($version) ](fg:#8A7144 bg:#1F1A13)]($style)'

[golang]
symbol = ""
style = "bg:#1F1A13"
format = '[[ $symbol ($version) ](fg:#8A7144 bg:#1F1A13)]($style)'

[php]
symbol = ""
style = "bg:#1F1A13"
format = '[[ $symbol ($version) ](fg:#8A7144 bg:#1F1A13)]($style)'

[time]
disabled = false
time_format = "%T"
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[localip]
style = "fg:#e3e5e5 bg:#A08A5A"
ssh_only = false
format = '[[ $localipv4 ](fg:#A08A5A bg:#1d2230)]($style)'
disabled = false

[os]
disabled = false
style = "bg:#E6D6A8 fg:#262015"


[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
EndeavourOS = "  "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "
Pop = "  "
